# -*- coding: utf-8 -*-


iso ={
    "AE":{"ISO":"AE","TLD":".ae","Name":"Abu Dhabi"},
    "AQ":{"ISO":"AQ","TLD":".aq","Name":"Adélieland"},
    "AE":{"ISO":"AE","TLD":".ae","Name":"Adschman"},
    "AF":{"ISO":"AF","TLD":".af","Name":"Afghanistan"},
    "EG":{"ISO":"EG","TLD":".eg","Name":"Ägypten"},
    "GB":{"ISO":"GB","TLD":".uk","Name":"Akrotiri"},
    "AX":{"ISO":"AX","TLD":".ax","Name":"_landinseln"},
    "US":{"ISO":"US","TLD":".us","Name":"Alaska"},
    "AL":{"ISO":"AL","TLD":".al","Name":"Albanien"},
    "GG":{"ISO":"GG","TLD":".gg","Name":"Alderney"},
    "US":{"ISO":"US","TLD":".us","Name":"Aleuten"},
    "DZ":{"ISO":"DZ","TLD":".dz","Name":"Algerien"},
    "VI":{"ISO":"VI","TLD":".vi","Name":"Amerikanische Jungferninseln"},
    "UM":{"ISO":"UM","TLD":".us","Name":"Amerikanisch-Ozeanien"},
    "AS":{"ISO":"AS","TLD":".as","Name":"Amerikanisch-Samoa"},
    "SC":{"ISO":"SC","TLD":".sc","Name":"Amiranten"},
    "IN":{"ISO":"IN","TLD":".in","Name":"Andamanen"},
    "AD":{"ISO":"AD","TLD":".ad","Name":"Andorra"},
    "AO":{"ISO":"AO","TLD":".ao","Name":"Angola"},
    "AI":{"ISO":"AI","TLD":".ai","Name":"Anguilla"},
    "AG":{"ISO":"AG","TLD":".ag","Name":"Antigua und Barbuda"},
    "GQ":{"ISO":"GQ","TLD":".gq","Name":"Äquatorialguinea"},
    "AR":{"ISO":"AR","TLD":".ar","Name":"Argentinien"},
    "AQ":{"ISO":"AQ","TLD":".aq","Name":"Argentinische Antarktis"},
    "AM":{"ISO":"AM","TLD":".am","Name":"Armenien"},
    "AW":{"ISO":"AW","TLD":".aw","Name":"Aruba"},
    "AM":{"ISO":"AM","TLD":".am","Name":"Arzwaschen"},
    "AC":{"ISO":"AC","TLD":".ac","Name":"Ascension"},
    "AZ":{"ISO":"AZ","TLD":".az","Name":"Aserbaidschan"},
    "AU":{"ISO":"AU","TLD":".au","Name":"Ashmore- und Cartierinseln"},
    "ET":{"ISO":"ET","TLD":".et","Name":"Äthiopien"},
    "ET":{"ISO":"ET","TLD":".et","Name":"Äthiopien (einschl. Eritrea)"},
    "AU":{"ISO":"AU","TLD":".au","Name":"Australien"},
    "PF":{"ISO":"PF","TLD":".pf","Name":"Australinseln"},
    "PT":{"ISO":"PT","TLD":".pt","Name":"Azoren"},
    "BS":{"ISO":"BS","TLD":".bs","Name":"Bahamas"},
    "BH":{"ISO":"BH","TLD":".bh","Name":"Bahrain"},
    "UM":{"ISO":"UM","TLD":".us","Name":"Bakerinsel"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Balearen"},
    "BD":{"ISO":"BD","TLD":".bd","Name":"Bangladesch"},
    "KG":{"ISO":"KG","TLD":".kg","Name":"Barak"},
    "BB":{"ISO":"BB","TLD":".bb","Name":"Barbados"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Bäreninsel"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Barentsinsel"},
    "AZ":{"ISO":"AZ","TLD":".az","Name":"Barxudarli"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Bassas da India"},
    "BE":{"ISO":"BE","TLD":".be","Name":"Belgien"},
    "BZ":{"ISO":"BZ","TLD":".bz","Name":"Belize"},
    "BJ":{"ISO":"BJ","TLD":".bj","Name":"Benin"},
    "BM":{"ISO":"BM","TLD":".bm","Name":"Bermuda"},
    "BT":{"ISO":"BT","TLD":".bt","Name":"Bhutan"},
    "PG":{"ISO":"PG","TLD":".pg","Name":"Bismarck-Archipel"},
    "BO":{"ISO":"BO","TLD":".bo","Name":"Bolivien"},
    "BQ":{"ISO":"BQ","TLD":".an","Name":"Bonaire Saint Eustatius und Saba"},
    "JP":{"ISO":"JP","TLD":".jp","Name":"Bonininseln"},
    "BA":{"ISO":"BA","TLD":".ba","Name":"Bosnien und Herzegowina"},
    "BW":{"ISO":"BW","TLD":".bw","Name":"Botsuana"},
    "BV":{"ISO":"BV","TLD":".bv","Name":"Bouvetinsel"},
    "BR":{"ISO":"BR","TLD":".br","Name":"Brasilien"},
    "VG":{"ISO":"VG","TLD":".vg","Name":"Britische Jungferninseln"},
    "IO":{"ISO":"IO","TLD":".io","Name":"Britisches Territorium im Indischen Ozean"},
    "BN":{"ISO":"BN","TLD":".bn","Name":"Brunei Darussalam"},
    "BG":{"ISO":"BG","TLD":".bg","Name":"Bulgarien"},
    "DE":{"ISO":"DE","TLD":".de","Name":"Bundesrepublik Deutschland "},
    "BF":{"ISO":"BF","TLD":".bf","Name":"Burkina Faso"},
    "BI":{"ISO":"BI","TLD":".bi","Name":"Burundi"},
    "DE":{"ISO":"DE","TLD":".de","Name":"Büsingen am Hochrhein"},
    "AO":{"ISO":"AO","TLD":".ao","Name":"Cabinda"},
    "TC":{"ISO":"TC","TLD":".tc","Name":"Caicosinseln"},
    "IT":{"ISO":"IT","TLD":".it","Name":"Campione d'Italia"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Ceuta"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Chafarinas"},
    "CL":{"ISO":"CL","TLD":".cl","Name":"Chile"},
    "AQ":{"ISO":"AQ","TLD":".aq","Name":"Chilenische Antarktis"},
    "CN":{"ISO":"CN","TLD":".cn","Name":"China"},
    "MW":{"ISO":"MW","TLD":".mw","Name":"Chizumuluinsel"},
    "UZ":{"ISO":"UZ","TLD":".uz","Name":"Chong-Kara"},
    "CP":{"ISO":"CP","TLD":".fr","Name":"Clipperton"},
    "EC":{"ISO":"EC","TLD":".ec","Name":"Colón"},
    "MT":{"ISO":"MT","TLD":".mt","Name":"Comino"},
    "CK":{"ISO":"CK","TLD":".ck","Name":"Cookinseln"},
    "CR":{"ISO":"CR","TLD":".cr","Name":"Costa Rica"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Crozetinseln"},
    "CW":{"ISO":"CW","TLD":".na","Name":"Curaçao"},
    "JP":{"ISO":"JP","TLD":".jp","Name":"Daitoinseln "},
    "DK":{"ISO":"DK","TLD":".dk","Name":"Dänemark"},
    "DD":{"ISO":"DD","TLD":".dd","Name":"Deutsche Demokratische Republik"},
    "DE":{"ISO":"DE","TLD":".de","Name":"Deutschland"},
    "GB":{"ISO":"GB","TLD":".uk","Name":"Dhekelia"},
    "DM":{"ISO":"DM","TLD":".dm","Name":"Dominica"},
    "DO":{"ISO":"DO","TLD":".do","Name":"Dominikanische Republik"},
    "DJ":{"ISO":"DJ","TLD":".dj","Name":"Dschibuti"},
    "AE":{"ISO":"AE","TLD":".ae","Name":"Dubai"},
    "HR":{"ISO":"HR","TLD":".hr","Name":"Dubrovnik-Neretva"},
    "PN":{"ISO":"PN","TLD":".pn","Name":"Ducie"},
    "EC":{"ISO":"EC","TLD":".ec","Name":"Ecuador"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Edgeinsel"},
    "SV":{"ISO":"SV","TLD":".sv","Name":"El Salvador"},
    "CI":{"ISO":"CI","TLD":".ci","Name":"Elfenbeinküste"},
    "GB":{"ISO":"GB","TLD":".uk","Name":"England"},
    "ER":{"ISO":"ER","TLD":".er","Name":"Eritrea"},
    "EE":{"ISO":"EE","TLD":".ee","Name":"Estland"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Europainsel"},
    "FK":{"ISO":"FK","TLD":".fk","Name":"Falklandinseln"},
    "FO":{"ISO":"FO","TLD":".fo","Name":"Färöer"},
    "FJ":{"ISO":"FJ","TLD":".fj","Name":"Fidschi"},
    "FI":{"ISO":"FI","TLD":".fi","Name":"Finnland"},
    "FR":{"ISO":"FR","TLD":".fr","Name":"Frankreich"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Französische Süd- u. Antarktisgebiete"},
    "GF":{"ISO":"GF","TLD":".gf","Name":"Französisch-Guayana"},
    "PF":{"ISO":"PF","TLD":".pf","Name":"Französisch-Polynesien"},
    "AE":{"ISO":"AE","TLD":".ae","Name":"Fudschaira"},
    "GA":{"ISO":"GA","TLD":".ga","Name":"Gabun"},
    "EC":{"ISO":"EC","TLD":".ec","Name":"Galápagosinseln"},
    "GM":{"ISO":"GM","TLD":".gm","Name":"Gambia"},
    "PF":{"ISO":"PF","TLD":".pf","Name":"Gambierinseln "},
    "PS":{"ISO":"PS","TLD":".ps","Name":"Gazastreifen"},
    "GE":{"ISO":"GE","TLD":".ge","Name":"Georgien"},
    "PF":{"ISO":"PF","TLD":".pf","Name":"Gesellschaftsinseln"},
    "GH":{"ISO":"GH","TLD":".gh","Name":"Ghana"},
    "GI":{"ISO":"GI","TLD":".gi","Name":"Gibraltar"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Glorieuses"},
    "MT":{"ISO":"MT","TLD":".mt","Name":"Gozo"},
    "AQ":{"ISO":"AQ","TLD":".aq","Name":"Grahamland"},
    "GD":{"ISO":"GD","TLD":".gd","Name":"Grenada"},
    "GR":{"ISO":"GR","TLD":".gr","Name":"Griechenland"},
    "GL":{"ISO":"GL","TLD":".gl","Name":"Grönland"},
    "GB":{"ISO":"GB","TLD":".uk","Name":"Großbritannien"},
    "GP":{"ISO":"GP","TLD":".gp","Name":"Guadeloupe"},
    "GU":{"ISO":"GU","TLD":".gu","Name":"Guam"},
    "US":{"ISO":"US","TLD":".us","Name":"Guantánamo"},
    "GT":{"ISO":"GT","TLD":".gt","Name":"Guatemala"},
    "GG":{"ISO":"GG","TLD":".gg","Name":"Guernsey"},
    "GN":{"ISO":"GN","TLD":".gn","Name":"Guinea"},
    "GW":{"ISO":"GW","TLD":".gw","Name":"Guinea-Bissau"},
    "GY":{"ISO":"GY","TLD":".gy","Name":"Guyana"},
    "HT":{"ISO":"HT","TLD":".ht","Name":"Haiti"},
    "US":{"ISO":"US","TLD":".us","Name":"Hawaii"},
    "HM":{"ISO":"HM","TLD":".hm","Name":"Heard und McDonaldinseln"},
    "PN":{"ISO":"PN","TLD":".pn","Name":"Henderson"},
    "NL":{"ISO":"NL","TLD":".nl","Name":"Holland"},
    "HN":{"ISO":"HN","TLD":".hn","Name":"Honduras"},
    "HK":{"ISO":"HK","TLD":".hk","Name":"Hong Kong"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Hopen"},
    "UM":{"ISO":"UM","TLD":".us","Name":"Howlandinsel"},
    "MA":{"ISO":"MA","TLD":".ma","Name":"Ifni"},
    "IN":{"ISO":"IN","TLD":".in","Name":"Indien"},
    "ID":{"ISO":"ID","TLD":".id","Name":"Indonesien"},
    "IM":{"ISO":"IM","TLD":".im","Name":"Insel Man"},
    "XC":{"ISO":"XC","TLD":"","Name":"International"},
    "IQ":{"ISO":"IQ","TLD":".iq","Name":"Irak"},
    "IR":{"ISO":"IR","TLD":".ir","Name":"Iran"},
    "ID":{"ISO":"ID","TLD":".id","Name":"Irian Jaya"},
    "IE":{"ISO":"IE","TLD":".ie","Name":"Irland"},
    "AR":{"ISO":"AR","TLD":".ar","Name":"Isla Martín García"},
    "IS":{"ISO":"IS","TLD":".is","Name":"Island"},
    "IL":{"ISO":"IL","TLD":".il","Name":"Israel"},
    "IT":{"ISO":"IT","TLD":".it","Name":"Italien"},
    "JM":{"ISO":"JM","TLD":".jm","Name":"Jamaika"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Jan Mayen"},
    "UZ":{"ISO":"UZ","TLD":".uz","Name":"Jangail"},
    "JP":{"ISO":"JP","TLD":".jp","Name":"Japan"},
    "UM":{"ISO":"UM","TLD":".us","Name":"Jarvisinsel"},
    "YE":{"ISO":"YE","TLD":".ye","Name":"Jemen"},
    "YE":{"ISO":"YE","TLD":"","Name":"Jemen (Nord)"},
    "YD":{"ISO":"YD","TLD":"","Name":"Jemen (Süd)"},
    "JE":{"ISO":"JE","TLD":".je","Name":"Jersey"},
    "UM":{"ISO":"UM","TLD":".us","Name":"Johnstoninsel"},
    "JO":{"ISO":"JO","TLD":".jo","Name":"Jordanien"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Juan da Nova"},
    "YU":{"ISO":"YU","TLD":".yu","Name":"Jugoslawien"},
    "KY":{"ISO":"KY","TLD":".ky","Name":"Kaimaninseln"},
    "RU":{"ISO":"RU","TLD":".ru","Name":"Kaliningrad"},
    "KH":{"ISO":"KH","TLD":".kh","Name":"Kambodscha"},
    "CM":{"ISO":"CM","TLD":".cm","Name":"Kamerun"},
    "CA":{"ISO":"CA","TLD":".ca","Name":"Kanada"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Kanarische Inseln "},
    "CV":{"ISO":"CV","TLD":".cv","Name":"Kap Verde"},
    "AZ":{"ISO":"AZ","TLD":".az","Name":"Karki"},
    "KZ":{"ISO":"KZ","TLD":".kz","Name":"Kasachstan"},
    "QA":{"ISO":"QA","TLD":".qa","Name":"Katar"},
    "CC":{"ISO":"CC","TLD":".cc","Name":"Keelinginseln"},
    "KE":{"ISO":"KE","TLD":".ke","Name":"Kenia"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Kerguelen"},
    "UM":{"ISO":"UM","TLD":".us","Name":"Kingmanriff"},
    "KG":{"ISO":"KG","TLD":".kg","Name":"Kirgisistan"},
    "KI":{"ISO":"KI","TLD":".ki","Name":"Kiribati"},
    "CC":{"ISO":"CC","TLD":".cc","Name":"Kokosinseln"},
    "CO":{"ISO":"CO","TLD":".co","Name":"Kolumbien"},
    "RU":{"ISO":"RU","TLD":".ru","Name":"Kommandeurinseln"},
    "KM":{"ISO":"KM","TLD":".km","Name":"Komoren"},
    "CG":{"ISO":"CG","TLD":".cg","Name":"Kongo (Brazzaville)"},
    "CD":{"ISO":"CD","TLD":".cd","Name":"Kongo (Kinshasa)"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"König-Karl-Land"},
    "XB":{"ISO":"XB","TLD":"","Name":"Konventionsflüchtling"},
    "AU":{"ISO":"AU","TLD":".au","Name":"Korallenmeerinseln"},
    "KP":{"ISO":"KP","TLD":".kp","Name":"Korea (Nord)"},
    "KR":{"ISO":"KR","TLD":".kr","Name":"Korea (Süd)"},
    "XK":{"ISO":"XK","TLD":"","Name":"Kosovo"},
    "HR":{"ISO":"HR","TLD":".hr","Name":"Kroatien"},
    "CU":{"ISO":"CU","TLD":".cu","Name":"Kuba"},
    "KW":{"ISO":"KW","TLD":".kw","Name":"Kuwait"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Kvitöya"},
    "GP":{"ISO":"GP","TLD":".gp","Name":"La Désirade"},
    "CA":{"ISO":"CA","TLD":".ca","Name":"Labrador"},
    "MY":{"ISO":"MY","TLD":".my","Name":"Labuan"},
    "TV":{"ISO":"TV","TLD":".tv","Name":"Laguneninseln"},
    "LA":{"ISO":"LA","TLD":".la","Name":"Laos"},
    "GP":{"ISO":"GP","TLD":".gp","Name":"Les Saintes "},
    "LS":{"ISO":"LS","TLD":".ls","Name":"Lesotho"},
    "LV":{"ISO":"LV","TLD":".lv","Name":"Lettland"},
    "LB":{"ISO":"LB","TLD":".lb","Name":"Libanon"},
    "LR":{"ISO":"LR","TLD":".lr","Name":"Liberia"},
    "LY":{"ISO":"LY","TLD":".ly","Name":"Libyen"},
    "LY":{"ISO":"LY","TLD":".ly","Name":"Libyen"},
    "LI":{"ISO":"LI","TLD":".li","Name":"Liechtenstein"},
    "MW":{"ISO":"MW","TLD":".mw","Name":"Likoma"},
    "LT":{"ISO":"LT","TLD":".lt","Name":"Litauen"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Llívia"},
    "LU":{"ISO":"LU","TLD":".lu","Name":"Luxemburg"},
    "MO":{"ISO":"MO","TLD":".mo","Name":"Macau"},
    "MG":{"ISO":"MG","TLD":".mg","Name":"Madagaskar"},
    "PT":{"ISO":"PT","TLD":".pt","Name":"Madeira"},
    "OM":{"ISO":"OM","TLD":".om","Name":"Madha"},
    "MW":{"ISO":"MW","TLD":".mw","Name":"Malawi"},
    "MY":{"ISO":"MY","TLD":".my","Name":"Malaysia"},
    "MV":{"ISO":"MV","TLD":".mv","Name":"Malediven"},
    "ML":{"ISO":"ML","TLD":".ml","Name":"Mali"},
    "MT":{"ISO":"MT","TLD":".mt","Name":"Malta"},
    "JP":{"ISO":"JP","TLD":".jp","Name":"Marcusinsel"},
    "GP":{"ISO":"GP","TLD":".gp","Name":"Marie-Galante"},
    "ZA":{"ISO":"ZA","TLD":".za","Name":"Marioninsel"},
    "MA":{"ISO":"MA","TLD":".ma","Name":"Marokko"},
    "PF":{"ISO":"PF","TLD":".pf","Name":"Marquesasinseln"},
    "MH":{"ISO":"MH","TLD":".mh","Name":"Marshallinseln"},
    "MQ":{"ISO":"MQ","TLD":".mq","Name":"Martinique"},
    "MR":{"ISO":"MR","TLD":".mr","Name":"Mauretanien"},
    "MU":{"ISO":"MU","TLD":".mu","Name":"Mauritius"},
    "YT":{"ISO":"YT","TLD":".yt","Name":"Mayotte"},
    "MK":{"ISO":"MK","TLD":".mk","Name":"Mazedonien"},
    "HM":{"ISO":"HM","TLD":".hm","Name":"McDonaldinseln"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Melilla"},
    "MX":{"ISO":"MX","TLD":".mx","Name":"Mexiko"},
    "UM":{"ISO":"UM","TLD":".us","Name":"Midwayinseln"},
    "FM":{"ISO":"FM","TLD":".fm","Name":"Mikronesien"},
    "PM":{"ISO":"PM","TLD":".pm","Name":"Miquelon"},
    "MD":{"ISO":"MD","TLD":".md","Name":"Moldau"},
    "MC":{"ISO":"MC","TLD":".mc","Name":"Monaco"},
    "MN":{"ISO":"MN","TLD":".mn","Name":"Mongolei"},
    "ME":{"ISO":"ME","TLD":".me","Name":"Montenegro "},
    "MS":{"ISO":"MS","TLD":".ms","Name":"Montserrat"},
    "MZ":{"ISO":"MZ","TLD":".mz","Name":"Mosambik"},
    "OM":{"ISO":"OM","TLD":".om","Name":"Musandam"},
    "MM":{"ISO":"MM","TLD":".mm","Name":"Myanmar"},
    "AZ":{"ISO":"AZ","TLD":".az","Name":"Nachitschewan"},
    "AE":{"ISO":"AE","TLD":".ae","Name":"Nahwa"},
    "NA":{"ISO":"NA","TLD":".na","Name":"Namibia"},
    "NR":{"ISO":"NR","TLD":".nr","Name":"Nauru"},
    "US":{"ISO":"US","TLD":".us","Name":"Navassa"},
    "NP":{"ISO":"NP","TLD":".np","Name":"Nepal"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Neuamsterdam"},
    "CA":{"ISO":"CA","TLD":".ca","Name":"Neufundland"},
    "NC":{"ISO":"NC","TLD":".nc","Name":"Neukaledonien"},
    "NZ":{"ISO":"NZ","TLD":".nz","Name":"Neuseeland"},
    "NT":{"ISO":"NT","TLD":"","Name":"Neutrale Zone"},
    "NI":{"ISO":"NI","TLD":".ni","Name":"Nicaragua"},
    "NL":{"ISO":"NL","TLD":".nl","Name":"Niederlande"},
    "AN":{"ISO":"AN","TLD":".na","Name":"Niederländische Antillen"},
    "NE":{"ISO":"NE","TLD":".ne","Name":"Niger"},
    "NG":{"ISO":"NG","TLD":".ng","Name":"Nigeria"},
    "IN":{"ISO":"IN","TLD":".in","Name":"Nikobaren"},
    "NU":{"ISO":"NU","TLD":".nu","Name":"Niue"},
    "GB":{"ISO":"GB","TLD":".uk","Name":"Nordirland"},
    "MP":{"ISO":"MP","TLD":".mp","Name":"Nördliche Marianen"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Nordostland"},
    "CY":{"ISO":"CY","TLD":".tr","Name":"Nordzypern"},
    "NF":{"ISO":"NF","TLD":".nf","Name":"Norfolkinseln"},
    "US":{"ISO":"US","TLD":".us","Name":"Nortwest Angle"},
    "NO":{"ISO":"NO","TLD":".no","Name":"Norwegen"},
    "TL":{"ISO":"TL","TLD":".tp","Name":"Oecusse"},
    "PN":{"ISO":"PN","TLD":".pn","Name":"Oeno"},
    "JP":{"ISO":"JP","TLD":".jp","Name":"Okinawa"},
    "OM":{"ISO":"OM","TLD":".om","Name":"Oman"},
    "CL":{"ISO":"CL","TLD":".cl","Name":"Osterinsel"},
    "AT":{"ISO":"AT","TLD":".at","Name":"Österreich"},
    "PK":{"ISO":"PK","TLD":".pk","Name":"Pakistan"},
    "PW":{"ISO":"PW","TLD":".pw","Name":"Palau"},
    "UM":{"ISO":"UM","TLD":".us","Name":"Palmyrainsel"},
    "PA":{"ISO":"PA","TLD":".pa","Name":"Panama"},
    "PG":{"ISO":"PG","TLD":".pg","Name":"Papua-Neuguinea"},
    "PY":{"ISO":"PY","TLD":".py","Name":"Paraguay"},
    "JP":{"ISO":"JP","TLD":".jp","Name":"Parece Vela"},
    "TZ":{"ISO":"TZ","TLD":".tz","Name":"Pemba"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Pe_ón de Alhucemas"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Pe_ón de Vélez de la Gomera"},
    "PE":{"ISO":"PE","TLD":".pe","Name":"Peru"},
    "PH":{"ISO":"PH","TLD":".ph","Name":"Philippinen"},
    "PN":{"ISO":"PN","TLD":".pn","Name":"Pitcairninseln"},
    "US":{"ISO":"US","TLD":".us","Name":"Point Roberts"},
    "PL":{"ISO":"PL","TLD":".pl","Name":"Polen"},
    "PT":{"ISO":"PT","TLD":".pt","Name":"Portugal"},
    "ZA":{"ISO":"ZA","TLD":".za","Name":"Prinz-Eduard Insel"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Prinz-Karl-Vorland"},
    "PR":{"ISO":"PR","TLD":".pr","Name":"Puerto Rico"},
    "AE":{"ISO":"AE","TLD":".ae","Name":"Ras al Chaima"},
    "BA":{"ISO":"BA","TLD":".ba","Name":"Republika Srpska"},
    "RE":{"ISO":"RE","TLD":".re","Name":"Réunion"},
    "MA":{"ISO":"MA","TLD":".ma","Name":"Río de Oro "},
    "JP":{"ISO":"JP","TLD":".jp","Name":"Riukiuinseln"},
    "CO":{"ISO":"CO","TLD":".co","Name":"Roncador"},
    "NZ":{"ISO":"NZ","TLD":".nz","Name":"Ross-Nebengebiet"},
    "RW":{"ISO":"RW","TLD":".rw","Name":"Ruanda"},
    "RO":{"ISO":"RO","TLD":".ro","Name":"Rumänien"},
    "RU":{"ISO":"RU","TLD":".ru","Name":"Russland"},
    "MY":{"ISO":"MY","TLD":".my","Name":"Sabah"},
    "MA":{"ISO":"MA","TLD":".ma","Name":"Saguia el Hamra"},
    "BL":{"ISO":"BL","TLD":".bl","Name":"Saint Barthélemy"},
    "SH":{"ISO":"SH","TLD":".sh","Name":"Saint Helena"},
    "KN":{"ISO":"KN","TLD":".kn","Name":"Saint Kitts und Nevis"},
    "LC":{"ISO":"LC","TLD":".lc","Name":"Saint Lucia"},
    "MF":{"ISO":"MF","TLD":".gp","Name":"Saint Martin"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Saint Paul "},
    "PM":{"ISO":"PM","TLD":".pm","Name":"Saint Pierre und Miquelon"},
    "VC":{"ISO":"VC","TLD":".vc","Name":"Saint Vincent und die Grenadinen"},
    "SB":{"ISO":"SB","TLD":".sb","Name":"Salomonen"},
    "ZM":{"ISO":"ZM","TLD":".zm","Name":"Sambia"},
    "WS":{"ISO":"WS","TLD":".ws","Name":"Samoa"},
    "SM":{"ISO":"SM","TLD":".sm","Name":"San Marino"},
    "TZ":{"ISO":"TZ","TLD":".tz","Name":"Sansibar"},
    "ST":{"ISO":"ST","TLD":".st","Name":"S_o Tomé und Princípe"},
    "MY":{"ISO":"MY","TLD":".my","Name":"Sarawak"},
    "GG":{"ISO":"GG","TLD":".gg","Name":"Sark"},
    "TJ":{"ISO":"TJ","TLD":".tj","Name":"Sarvan"},
    "BA":{"ISO":"BA","TLD":".ba","Name":"Sastavci"},
    "SA":{"ISO":"SA","TLD":".sa","Name":"Saudi-Arabien"},
    "AE":{"ISO":"AE","TLD":".ae","Name":"Schardscha"},
    "GB":{"ISO":"GB","TLD":".uk","Name":"Schottland"},
    "HN":{"ISO":"HN","TLD":".hn","Name":"Schwaneninseln "},
    "SE":{"ISO":"SE","TLD":".se","Name":"Schweden"},
    "CH":{"ISO":"CH","TLD":".ch","Name":"Schweiz"},
    "SN":{"ISO":"SN","TLD":".sn","Name":"Senegal"},
    "RS":{"ISO":"RS","TLD":".rs","Name":"Serbien "},
    "CS":{"ISO":"CS","TLD":".yu","Name":"Serbien und Montenegro"},
    "CO":{"ISO":"CO","TLD":".co","Name":"Serranabank"},
    "SC":{"ISO":"SC","TLD":".sc","Name":"Seychellen"},
    "UZ":{"ISO":"UZ","TLD":".uz","Name":"Shohimardon"},
    "SL":{"ISO":"SL","TLD":".sl","Name":"Sierra Leone"},
    "IN":{"ISO":"IN","TLD":".in","Name":"Sikkim"},
    "ZW":{"ISO":"ZW","TLD":".zw","Name":"Simbabwe"},
    "SG":{"ISO":"SG","TLD":".sg","Name":"Singapur"},
    "SX":{"ISO":"SX","TLD":".an","Name":"Sint Maarten "},
    "SK":{"ISO":"SK","TLD":".sk","Name":"Slowakei"},
    "SI":{"ISO":"SI","TLD":".si","Name":"Slowenien"},
    "YE":{"ISO":"YE","TLD":".ye","Name":"Sokotra"},
    "SO":{"ISO":"SO","TLD":".so","Name":"Somalia"},
    "SO":{"ISO":"SO","TLD":".so","Name":"Somaliland"},
    "SU":{"ISO":"SU","TLD":".su","Name":"Sowjetunion"},
    "UZ":{"ISO":"UZ","TLD":".uz","Name":"So'x"},
    "ES":{"ISO":"ES","TLD":".es","Name":"Spanien"},
    "MA":{"ISO":"MA","TLD":".ma","Name":"Spanische Sahara"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Spitzbergen"},
    "LK":{"ISO":"LK","TLD":".lk","Name":"Sri Lanka"},
    "XA":{"ISO":"XA","TLD":"","Name":"Staatenlos"},
    "ZA":{"ISO":"ZA","TLD":".za","Name":"Südafrika"},
    "SD":{"ISO":"SD","TLD":".sd","Name":"Sudan"},
    "SD":{"ISO":"SD","TLD":".sd","Name":"Sudan"},
    "GS":{"ISO":"GS","TLD":".gs","Name":"Südgeorgien"},
    "GS":{"ISO":"GS","TLD":".gs","Name":"Südliche Orkneyinseln "},
    "GS":{"ISO":"GS","TLD":".gs","Name":"Südliche Sandwichinseln"},
    "AQ":{"ISO":"AQ","TLD":".aq","Name":"Südliche Shetlandinseln "},
    "SS":{"ISO":"SS","TLD":".ss","Name":"Südsudan"},
    "SR":{"ISO":"SR","TLD":".sr","Name":"Suriname"},
    "SJ":{"ISO":"SJ","TLD":".no","Name":"Svalbard und Jan Mayen"},
    "SZ":{"ISO":"SZ","TLD":".sz","Name":"Swasiland"},
    "SY":{"ISO":"SY","TLD":".sy","Name":"Syrien"},
    "TJ":{"ISO":"TJ","TLD":".tj","Name":"Tadschikistan"},
    "PF":{"ISO":"PF","TLD":".pf","Name":"Tahiti"},
    "TW":{"ISO":"TW","TLD":".tw","Name":"Taiwan"},
    "TZ":{"ISO":"TZ","TLD":".tz","Name":"Tanganjika"},
    "TZ":{"ISO":"TZ","TLD":".tz","Name":"Tansania"},
    "TH":{"ISO":"TH","TLD":".th","Name":"Thailand"},
    "CN":{"ISO":"CN","TLD":".cn","Name":"Tibet"},
    "TL":{"ISO":"TL","TLD":".tp","Name":"Timor-Leste"},
    "TT":{"ISO":"TT","TLD":".tt","Name":"Tobago"},
    "TG":{"ISO":"TG","TLD":".tg","Name":"Togo"},
    "TK":{"ISO":"TK","TLD":".tk","Name":"Tokelau"},
    "TO":{"ISO":"TO","TLD":".to","Name":"Tonga"},
    "MD":{"ISO":"MD","TLD":".md","Name":"Transnistrien"},
    "TT":{"ISO":"TT","TLD":".tt","Name":"Trinidad und Tobago"},
    "TA":{"ISO":"TA","TLD":".sh","Name":"Tristan da Cunha"},
    "TF":{"ISO":"TF","TLD":".tf","Name":"Tromelin"},
    "TD":{"ISO":"TD","TLD":".td","Name":"Tschad"},
    "IO":{"ISO":"IO","TLD":".io","Name":"Tschagos-Archipel"},
    "CZ":{"ISO":"CZ","TLD":".cz","Name":"Tschechien"},
    "CS":{"ISO":"CS","TLD":".cs","Name":"Tschechoslowakei"},
    "PF":{"ISO":"PF","TLD":".pf","Name":"Tuamotuinseln "},
    "PF":{"ISO":"PF","TLD":".pf","Name":"Tubuaiinseln"},
    "TN":{"ISO":"TN","TLD":".tn","Name":"Tunesien"},
    "TR":{"ISO":"TR","TLD":".tr","Name":"Türkei"},
    "TM":{"ISO":"TM","TLD":".tm","Name":"Turkmenistan"},
    "TC":{"ISO":"TC","TLD":".tc","Name":"Turks- und Caicosinseln"},
    "TV":{"ISO":"TV","TLD":".tv","Name":"Tuvalu"},
    "UG":{"ISO":"UG","TLD":".ug","Name":"Uganda"},
    "UA":{"ISO":"UA","TLD":".ua","Name":"Ukraine"},
    "AE":{"ISO":"AE","TLD":".ae","Name":"Umm al Kaiwain"},
    "XX":{"ISO":"XX","TLD":"","Name":"Unbekannt"},
    "HU":{"ISO":"HU","TLD":".hu","Name":"Ungarn"},
    "HU":{"ISO":"HU","TLD":".hu","Name":"Ungarn"},
    "XZ":{"ISO":"XZ","TLD":"","Name":"Ungeklärt"},
    "UY":{"ISO":"UY","TLD":".uy","Name":"Uruguay"},
    "UZ":{"ISO":"UZ","TLD":".uz","Name":"Usbekistan"},
    "VU":{"ISO":"VU","TLD":".vu","Name":"Vanuatu"},
    "VA":{"ISO":"VA","TLD":".va","Name":"Vatikan"},
    "VE":{"ISO":"VE","TLD":".ve","Name":"Venezuela"},
    "AE":{"ISO":"AE","TLD":".ae","Name":"Vereinigte Arabische Emirate"},
    "US":{"ISO":"US","TLD":".us","Name":"Vereinigte Staaten von Amerika"},
    "GB":{"ISO":"GB","TLD":".uk","Name":"Vereinigtes Königreich"},
    "VN":{"ISO":"VN","TLD":".vn","Name":"Vietnam"},
    "VN":{"ISO":"VN","TLD":"","Name":"Vietnam (Nord)"},
    "VD":{"ISO":"VD","TLD":"","Name":"Vietnam (Süd)"},
    "TJ":{"ISO":"TJ","TLD":".tj","Name":"Vorukh"},
    "JP":{"ISO":"JP","TLD":".jp","Name":"Vulkaninseln "},
    "UM":{"ISO":"UM","TLD":".us","Name":"Wakeinseln"},
    "GB":{"ISO":"GB","TLD":".uk","Name":"Wales"},
    "WF":{"ISO":"WF","TLD":".wf","Name":"Wallis und Futuna"},
    "CX":{"ISO":"CX","TLD":".cx","Name":"Weihnachtsinsel"},
    "BY":{"ISO":"BY","TLD":".by","Name":"Weißrussland"},
    "PS":{"ISO":"PS","TLD":".ps","Name":"Westjordanland"},
    "EH":{"ISO":"EH","TLD":".eh","Name":"Westsahara"},
    "AZ":{"ISO":"AZ","TLD":".az","Name":"Yukhary Askipara"},
    "ZR":{"ISO":"ZR","TLD":".zr","Name":"Zaire"},
    "CF":{"ISO":"CF","TLD":".cf","Name":"Zentralafrikanische Republik"},
    "CY":{"ISO":"CY","TLD":".cy","Name":"Zypern"}
	}